-- Migration 0074: smart playlists
-- ───────────────────────────────
-- docs/music-signals-and-smart-playlists-plan.md §4.
--
-- A smart playlist is **a saved query, an ordering and a refresh policy** — not
-- a list of track ids. `music_playlists` (0012) stays exactly as it is for
-- hand-made playlists; this is a sibling, not a replacement, because the two
-- answer different questions. A hand-made playlist is a decision someone made
-- once; a smart one is a decision they want re-made every time they open it.
--
-- WHY THE RULE IS JSONB AND NOT COLUMNS
--
-- The rule schema is small but it is a tree (ranges, include/exclude sets, a
-- limit that is either a count or a duration), and it will grow. Columns would
-- mean a migration per filter. It is validated in Rust against a closed schema
-- on every write — `music::rules::Rule` with `deny_unknown_fields` — so what
-- lands here is never arbitrary JSON, and `rule_version` says which schema it
-- was validated against.
--
-- That closed schema is also what makes it safe to accept a rule generated by
-- a language model (§5.1): the model emits a rule, never a tracklist, and a
-- rule that fails validation is refused rather than half-applied.
--
-- FROZEN VS DYNAMIC
--
-- `dynamic` re-evaluates on every open. `frozen` was materialised once into an
-- ordinary `music_playlists` row and is kept here only for provenance — "this
-- came from that rule" — which is what lets a client offer "refresh from the
-- rule" without guessing.

CREATE TABLE music_smart_playlists (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- NULL is private to the owner, set is shared with that family. Same
    -- convention as 0019, deliberately — a smart playlist is content.
    family_id    UUID        REFERENCES families (id) ON DELETE SET NULL,
    name         TEXT        NOT NULL,
    description  TEXT,
    rule         JSONB       NOT NULL,
    rule_version SMALLINT    NOT NULL DEFAULT 1,
    mode         TEXT        NOT NULL DEFAULT 'dynamic'
                             CHECK (mode IN ('dynamic', 'frozen')),
    -- Set when `mode = 'frozen'`: the ordinary playlist this was materialised
    -- into.
    frozen_into  UUID        REFERENCES music_playlists (id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX music_smart_playlists_user_idx ON music_smart_playlists (user_id, updated_at DESC);
CREATE INDEX music_smart_playlists_family_idx
    ON music_smart_playlists (family_id)
    WHERE family_id IS NOT NULL;
